spring:
  application:
   name: payments
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true


  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    consumer:
      group-id: ${apps.kafka.groupId}


apps:
  kafka:
    paymentTopic: ${TOPIC_PAYMENT_REQUEST}
    groupId: ${KAFKA_GROUP_ID}
    server: ${KAFKA_SERVER}
    mapping: ${NEW_PAYMENT_MAPPING}

